channels:
  - bioconda
  - conda-forge
dependencies:
  - compilers
  - cmake=3
  - gcc=9
  - python<=3.10
  - pip
  - pip:
      - bdsg
  - snakemake
  - pandas
  - numpy
  - scikit-learn
  - pytorch
  - pysam
  - singularity=3
  - minigraph
  - gfatools
  - seqkit
  - crossmap
  - vg
  - samtools
  - csvtk
  - bedtools
  - smoothxg
  - seqwish
  - gfaffix
  - kmc
  - bcftools
  - minimap2
  - hiphase
  - pangenie
  - hdf5
  - cutesv=2.1.1
  - truvari
  - meryl
  - bwa
  - gatk4
  - pbmm2
  - glnexus
  - whatshap=1.4
  - beagle=4.1
  - shapeit4
  - merfin
  - graphaligner
  - racon
  - pbgcpp
  - cutadapt
  - sniffles
  - jasminesv
  - freebayes

