Call_LR_SNV: true

samples: test_data/samples.list

lr_hifi_fastqs:
  - test_data/{sample}/{sample}.lr_hifi.fastq.gz

lr_zmw_fastqs:
  - test_data/{sample}/{sample}.lr_zmw.fastq.gz

#https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz
reference:
  CHM13: test_data/reference/chm13v2.0.fa

prefix: test
