Call_SR_SNV: true

samples: test_data/samples.list

sr_fastqs:
  - test_data/{sample}/{sample}.sr.R1.fastq.gz
  - test_data/{sample}/{sample}.sr.R2.fastq.gz

#https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/analysis_set/chm13v2.0.fa.gz
reference:
  CHM13: test_data/reference/chm13v2.0.fasta

GATK_Resource:
  hapmap: test_data/reference/gatk_bundle/hapmap_3.3.chm13_liftover.vcf.gz
  omni: test_data/reference/gatk_bundle/1000G_omni2.5.chm13_liftover.vcf.gz
  1000G: test_data/reference/gatk_bundle/1000G_phase1.snps.high_confidence.chm13_liftover.vcf.gz
  known_indel: test_data/reference/gatk_bundle/Homo_sapiens_assembly38.known_indels.chm13_liftover.vcf.gz
  mills: test_data/reference/gatk_bundle/Mills_and_1000G_gold_standard.indels.chm13_liftover.vcf.gz
  axiomPoly: test_data/reference/gatk_bundle/Axiom_Exome_Plus.genotypes.all_populations.poly.chm13_liftover.vcf.gz

prefix: test
