samples: test_data/samples.list

training_samples:
  - CKCG-00202

test_samples:
  - CKCG-00202

validate_samples:
  - CKCG-00202

sr_fastqs:
  - test_data/{sample}/{sample}.sr.R1.fastq.gz
  - test_data/{sample}/{sample}.sr.R2.fastq.gz

lr_hifi_fastqs:
  - test_data/{sample}/{sample}.lr_hifi.fastq.gz

lr_zmw_fastqs:
  - test_data/{sample}/{sample}.lr_zmw.fastq.gz

reference:
  CHM13: test_data/reference/chm13v2.0_maskedY_rCRS.fasta
  GRCh38: test_data/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.fai

kmer:
  CHM13: test_data/reference/CHM13_21mer_meryl/

GATK_Resource:
  hapmap: test_data/reference/gatk_bundle/hapmap_3.3.chm13_liftover.vcf.gz
  omni: test_data/reference/gatk_bundle/1000G_omni2.5.chm13_liftover.vcf.gz
  1000G: test_data/reference/gatk_bundle/1000G_phase1.snps.high_confidence.chm13_liftover.vcf.gz
  known_indel: test_data/reference/gatk_bundle/Homo_sapiens_assembly38.known_indels.chm13_liftover.vcf.gz
  mills: test_data/reference/gatk_bundle/Mills_and_1000G_gold_standard.indels.chm13_liftover.vcf.gz
  axiomPoly: test_data/reference/gatk_bundle/Axiom_Exome_Plus.genotypes.all_populations.poly.chm13_liftover.vcf.gz

genetic_map: "test_data/genetic_map/genetic_map_chm13_{chr}.reform.txt"

prefix: CKCG
