Generate_Personal_Reference: true

samples: test_data/samples.list

sr_fastqs:
  - test_data/{sample}/{sample}.sr.R1.fastq.gz
  - test_data/{sample}/{sample}.sr.R2.fastq.gz

lr_zmw_fastqs:
  - test_data/{sample}/{sample}.lr_zmw.fastq.gz

external_pangenome:
  - test_data/reference/hgsvc3-hprc-2024-02-23-mc-chm13.gbz

reference:
  CHM13: test_data/reference/chm13v2.0.fa

prefix: test
