Simplify_ML_Pangenome: true

reference:
    CHM13:
        test_data/reference/chm13v2.0_maskedY_rCRS.fasta
    GRCh38:
        test_data/reference/GRCh38_no_alt_analysis_set.fasta

train_sample_list:

prefix:
    test

phased_snv:

#?
model_dir:

#if no "linear_gfaffix_gfa" key, default input will be c7_graph_construction/chr_mc/{chr}/subgraph/subgraph{subgraph_id}/t2t.grch38.58hifi.1064zmw.{chr}.subgraph_{subgraph_id}.seqwish.smoothxg2.gfaffix.linearize.gfa
gfaffix_gfa: 


    
